import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import PromoBanner from "./components/PromoBanner";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";



import StoreProvider from "./store/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const integralCFBold = localFont({
  src: '../public/fonts/integralcf-bold.otf',
        variable: "--font-integralcf-bold",
      })
const satoshiRegular = localFont({
  src: '../public/fonts/satoshi-regular.otf',
  variable: "--font-satoshi-regular",
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${integralCFBold.variable} ${satoshiRegular.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <PromoBanner/>
          <Navbar/>
          {children}
          <Footer/>
        </StoreProvider>
      </body>
    </html>
  );
}
